<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="QAIT006" name="com.demo.tests.TestCase_01" tests="7" failures="1" timestamp="17 Feb 2020 17:34:11 GMT" time="5.450" errors="0">
  <testcase name="marketsPageProducts" time="0.187" classname="com.demo.tests.TestCase_01"/>
  <testcase name="clientInfo" time="0.216" classname="com.demo.tests.TestCase_01"/>
  <testcase name="products" time="0.232" classname="com.demo.tests.TestCase_01"/>
  <testcase name="convertCurrency" time="0.247" classname="com.demo.tests.TestCase_01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.demo.scripts.api.degiro.orders.CurrencyTransaction.currencyTransaction(CurrencyTransaction.java:111)
at com.demo.tests.TestCase_01.convertCurrency(TestCase_01.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- convertCurrency -->
  <testcase name="userLogin" time="0.443" classname="com.demo.tests.TestCase_01"/>
  <testcase name="currencyInfo" time="0.480" classname="com.demo.tests.TestCase_01"/>
  <testcase name="productsPopular" time="3.645" classname="com.demo.tests.TestCase_01"/>
</testsuite> <!-- com.demo.tests.TestCase_01 -->
